title: Jay Perry

shop: https://jayperry.etsy.com/

social:
  callout: Keep in touch. You can also find me on
  channels:
  - name: Etsy
    link: https://jayperry.etsy.com/
  - name: Twitter
    link: https://twitter.com/inkpixelswords
  - name: Pinterest
    link: https://www.pinterest.com/jayperryworks/
  - name: Github
    link: https://github.com/jayperryworks
