backend:
  name: github
  repo: jayperryworks/jayperryworks-site
  branch: install-netlify-cms # Branch to update (optional; defaults to master)

media_folder: 'source/assets/images/uploads' # Folder where user uploaded files should go
public_folder: '/assets/images'
site_url: https:/www.jayperryworks.com

publish_mode: editorial_workflow

collections:
  - name: 'writing' # Used in routes, e.g., /admin/collections/blog
    label: 'Writing' # Used in the UI
    folder: 'source/writing' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: html.md.erb
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
      - label: 'Featured image'
        name: 'image'
        widget: 'image'
      - label: 'Intro note'
        name: 'intro_note'
        widget: 'text'
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Short post'
        name: 'show_full'
        widget: 'boolean'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'work' # Used in routes, e.g., /admin/collections/blog
    label: 'Work' # Used in the UI
    folder: 'source/work' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: html.md
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Date'
        name: 'date'
        widget: 'date'
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - prints
          - paintings
        default: prints
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Cover image'
        name: 'cover'
        widget: 'image'
      - label: 'Thumbnail image'
        name: 'thumb'
        widget: 'image'
      - label: 'Editions'
        name: editions
        widget: list
        fields:
          - label: Edition
            name: edition
            widget: object
            fields:
              - label: Name (size)
                name: name
                widget: string
              - label: Type
                name: type
                widget: select
                default: giclee
                options:
                  - giclee
                  - screenprint
              - label: Height
                name: height
                widget: number
                valueType: int
              - label: Width
                name: width
                widget: number
                valueType: int
              - label: Border
                name: border
                widget: number
                valueType: int
                default: 1
              - label: Price
                name: price
                valueType: int
              - label: Image
                name: image
                widget: image
              - label: Etsy listing
                name: url
                widget: string
      - label: 'Body'
        name: 'body'
        widget: 'markdown'

  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About'
        file: 'source/about.html.md.erb'
        extension: html.md.erb
        format: frontmatter
        create: false
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Layout'
            name: 'layout'
            widget: 'hidden'
            default: 'blog_post'
          - label: 'Featured image'
            name: 'image'
            widget: 'image'
          - label: 'Hide footer bio'
            name: 'hide_bio'
            widget: 'hidden'
            default: true
